version: '1.0'

# PLAYER_FLYING_MODE : decrement fly when player fly
# PLAYER_FLY_MODE : decrement fly when player active /fly
fly-decrement-method: PLAYER_FLY_MODE

format-placeholder:
  seconds: true
  minutes: true
  hours: true
  days: true
  auto-format: true
  format: "%seconds% %minutes% %hours% %days%"