##############################################################################################
#                                            WFLY PLUGIN                                     #
##                                                                                           #
#   Documentation : https://app.gitbook.com/o/ew6PbMsQsqKjVC6kUf22/s/wnts7HZ5JI6Nxy4VSXbq/   #
#                                                                                            #
##############################################################################################

# NOTE : If you are using spigot server, you can't use Minimessage, you must use HexaDecimals format
# Example : #FFC77AHello!

version: '1.02'

save-database-delay: 60 # in seconds

#see docs for more info
fly-decrement-method: PLAYER_FLY_MODE

format-placeholder:
  seconds: true
  minutes: false
  hours: true
  days: true
  unlimited: "Unlimited" #need permission wfly.infinite.fly
  auto-format: true
  remove-null-values:
    enabled: true
    value: "0"
  format: "#FFC77A%seconds%#FF9D00%seconds_suffixe%#FFC77A%minutes%#FF9D00%minutes_suffixe% #FFC77A%hours%#FF9D00%hours_suffixe% #FFC77A%days%#FF9D00%days_suffixe%"
  other-format:
    seconds_suffixe: "seconds"
    minutes_suffixe: "minutes"
    hours_suffixe: "hours"
    days_suffixe: "days"


#EXAMPLE OF CONDITIONS
#mean if condition is valid, players will can't activate her fly
conditions:
  not-authorized: # refer if matched, player can't fly
    my-first-conditions:
      placeholder: "%multiverse_world_alias%"
      equals: "world" #player can't fly in this world
      command: ""
  authorized: # refer if matched, player can fly
    my-seconds-conditions:
      placeholder: "%multiverse_world_alias%"
      equals: "world_nether" #player can fly in this world


#NOTE : authorized section override not-authorized section
# If authorized section is true for player(just 1), player can fly
