##############################################################################################
#                                            WFLY PLUGIN                                     #
##                                                                                           #
#   Documentation : https://app.gitbook.com/o/ew6PbMsQsqKjVC6kUf22/s/wnts7HZ5JI6Nxy4VSXbq/   #
#                                                                                            #
##############################################################################################
version: '1.0'

fly-decrement-method: PLAYER_FLY_MODE

format-placeholder:
  seconds: true
  minutes: false
  hours: true
  days: true
  auto-format: true
  format: "<#FFC77A>%seconds%<#FF9D00>%seconds_suffixe% <#FFC77A>%minutes%<#FF9D00>%minutes_suffixe% <#FFC77A>%hours%<#FF9D00>%hours_suffixe% <#FFC77A>%days%<#FF9D00>%days_suffixe%"
  other-format:
    seconds_suffixe: "seconds"
    minutes_suffixe: "minutes"
    hours_suffixe: "hours"
    days_suffixe: "days"


#mean if condition is valid, player will can't activate his fly
conditions:
  my-first-conditions:
    placeholder: "%player_name%"
    equals: "Wayvi2"



